### PR TITLE
Removed beacons from stations and added telescope stealth

### PR DESCRIPTION
**Pull request by tsoj**
"This is an attempt at an invisible shipdata.plist  
Seems to work on my AppleMac!  
Good for the Scanner, Telescope & the Galactic Almanac"

This pull request has been written by @Cholmondely-of-Digebiti.

### CODE REVIEW

**Comment by tsoj** [comment]
@Cholmondely-of-Digebiti if you click on the tab "Files changed" you will see the files that I changed with this pull request. The red highlighted lines are lines that will be removed, and green lines will be added. If you look through them, you should see your changes. I made them by hand, because when I copied the code you pasted into the issue, I got some formatting issues. So it would be good if you made sure that I didn't miss any changes that you made.

In the part `himsn_headquarters` you added a "script_info" object. However, there already was one such object, but with `"stationOrientation" = "planet";` in it. I believe Oolite only looks at the first script_info and discards the rest.

A solution could be to do it like this:
```javascript
script_info = {
	"stationOrientation" = "planet";
	telescope = 0;
};
```
I assume that this `telescope = 0` does the trick for making it invisible to the telescope OXP, right? Is there a reason why only `himsn_headquarters`gets this stealth, but not `himsn_system_base` or `himsn_interstellar_outpost`?  
Should maybe the beacon of the carrier be removed (so that it stays consistent once we add the Komodo carrier to the game play)?

**Comment by User-Cody** [comment]
"Should maybe the beacon of the carrier be removed (so that it stays consistent once we add the Komodo carrier to the game play)?"
Yes, seems logical.

**Comment by Cholmondely-of-Digebiti** [comment]
So, being merely a "dumb pilot" (in the words of my mighty and magnificent mentor), I searched our wiki and found _nothing_, and then peered inside the Hermit descriptions (in vanilla, Spicy Hermits.oxp & Pirate Coves.oxp: looking for where hermits are given beacons of variable strength) and also found _nothing_.

So I experimented with removing the two beacon lines and it worked!

Then I included the 3 code lines from [[cag's pm](http://www.aegidian.org/bb/viewtopic.php?p=281264#p281264)](url):
`
 script_info = {
 	telescope = 0;
 };
`
Since the other bases seemed to use the first as a template (like_ship = "himsn_headquarters";), I presumed that that was enough, once I'd removed their beacon names too.

Again, it worked!


So please, re-jig as you suggest... you know _much_ more about this than I do. I just desperately wanted to try it out and see if I could get it to work (everything else seems to fail dismally...!)

**Note**:
On a more recent flight I discovered these error lines (http://www.aegidian.org/bb/viewtopic.php?p=281329#p281329) which I'd not seen in earlier play-throughs).

**Comment by tsoj** [comment]
@Cholmondely-of-Digebiti 
I just missed that the other bases are using the template. So that will stay how it is.  
I removed the beacon from the carrier, (probably) fixed the ball turret range warning, and merged the two script_infos (how I already mentioned).  
I will try to take a look at how a short-range beacon could be done, but for now, I'll just add these changes.

**Comment by tsoj** [comment]
I just need to test something:
@dariusduesentrieb

**Pull request merged**
